name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: ${{matrix.os}}/${{matrix.build-type}}
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v2
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        run: |
          cmake .. `
            -DSOURCE_URL=https://github.com/${{github.repository}} `
            -DSOURCE_REF=${{github.sha}} `
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} `
            -DCMAKE_OSX_ARCHITECTURES=${{matrix.arch}} `
            "-DCMAKE_INSTALL_PREFIX=${{runner.temp}}/install"
        shell: pwsh
      - name: Compile
        working-directory: build
        run: cmake --build . --parallel --config ${{matrix.build-type}}
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.build-type}}
      - name: Upload AudioDeviceLib.cmake
        uses: actions/upload-artifact@v2
        with:
          name: AudioDeviceLib.cmake
          path: build/AudioDeviceLib.cmake
      - name: Upload Demos
        uses: actions/upload-artifact@v2
        with:
          name: demos-${{matrix.os}}-${{matrix.build-type}}.cmake
          path: ${{runner.temp}}/install/demos/*
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos-arm64, macos-x86_64]
        build-type: [RelWithDebInfo, Debug]
        include:
          - os: windows
            runs-on: windows-latest
          - os: macos-arm64
            arch: arm64
            runs-on: macos-latest
          - os: macos-x86_64
            arch: x86_64
            runs-on: macos-latest
